project:
  type: website

website:
  title: actxps
  navbar:
    background: primary
    search: true
    left:
      - text: "Get started"
        file: articles/actxps.qmd
      - text: "Reference"
        file: reference/index.qmd
      - text: "Articles"
        menu:
        - text: "Exposure calculations"
          file: articles/exposures.qmd
        - text: "Experience summaries"
          file: articles/exp_summary.qmd
        - text: "Transaction studies"
          file: articles/transactions.qmd
        - text: "Data visualizations"
          file: articles/visualizations.qmd
        - text: "Other functions"
          file: articles/misc.qmd
      - href: changelog.qmd
        text: Changelog
    right:
      - icon: github
        href: https://github.com/mattheaphy/actxpspy
      - icon: r-circle-fill
        menu:
        - text: "R version of actxps"
        - href: https://github.com/mattheaphy/actxps
          text: Source code
        - href: https://mattheaphy.github.io/actxps
          text: Package documentation

format:
  html:
    theme: zephyr
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: actxps

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: "Exposure calculations"
      desc: "Convert census records to exposure records"
      contents:
        - expose
